# Generated by Django 3.2.13 on 2022-11-04 08:52

import audit_logger.data
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logger_name",
                    models.CharField(max_length=100, verbose_name="Logger name"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "NotSet"),
                            (20, "Info"),
                            (30, "Warning"),
                            (10, "Debug"),
                            (40, "Error"),
                            (50, "Fatal"),
                        ],
                        db_index=True,
                        default=40,
                        verbose_name="Logging level",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Is sent")),
                (
                    "message",
                    models.JSONField(
                        encoder=audit_logger.data.AuditMessageEncoder,
                        verbose_name="Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("trace", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Audit logging",
                "verbose_name_plural": "Audit logging",
                "ordering": ("-created_at",),
            },
        ),
    ]
