# Generated by Django 3.2.13 on 2022-11-04 08:26

import audit_logger.data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="trace",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="message",
            field=models.JSONField(
                encoder=audit_logger.data.AuditMessageEncoder, verbose_name="Message"
            ),
        ),
    ]
