minimum_pre_commit_version: 4.2.0 # You MUST keep this version in sync with the version in requirements-dev.in
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0 # You MUST keep this version in sync with the version in requirements-dev.in
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0 # You MUST keep this version in sync with the version in requirements-dev.in
    hooks:
      - id: flake8

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1 # You MUST keep this version in sync with the version in requirements-dev.in
    hooks:
      - id: isort
