services:
  db:
    platform: linux/amd64
    image: postgis/postgis:14-3.5
    volumes:
      - database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: parking_permits_db
      POSTGRES_USER: parking_permits_user
      POSTGRES_PASSWORD: parking_permits_password
    ports:
      - "127.0.0.1:5555:5432"
    container_name: parking-permits-database

  api:
    platform: linux/amd64
    image: parking_permits_api
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/app:cached
    ports:
      - "127.0.0.1:8888:8888"
    container_name: parking-permits-api


  mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      volumes:
          - ./data:/data
      ports:
          - 8025:8025
          - 1025:1025
      environment:
          MP_MAX_MESSAGES: 5000
          MP_DATABASE: /data/mailpit.db
          MP_SMTP_AUTH_ACCEPT_ANY: 1
          MP_SMTP_AUTH_ALLOW_INSECURE: 1


volumes:
  database-volume: {}

networks:
  default:
    name: helsinki
