version: "3.9"

services:
  db:
    image: postgis/postgis:13-3.1
    volumes:
      - database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: parking_permits_db
      POSTGRES_USER: parking_permits_user
      POSTGRES_PASSWORD: parking_permits_password
    ports:
      - "127.0.0.1:5555:5432"
    container_name: parking-permits-database

  api:
    image: parking_permits_api
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:cached
    ports:
      - "127.0.0.1:8888:8888"
    container_name: parking-permits-api

volumes:
  database-volume: {}

networks:
  default:
    name: helsinki
