version: "3.9"

services:
  database:
    # https://registry.hub.docker.com/r/postgis/postgis
    image: postgis/postgis:13-3.1
    volumes:
      - database-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_postgres_db
      POSTGRES_USER: my_postgres_user
      POSTGRES_PASSWORD: my_postgres_password
    ports:
      - "127.0.0.1:5555:5432"

  api:
    build:
      context: .
      target: development_stage
    volumes:
      - .:/app:cached
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DEBUG=true
      - DEV_SERVER=true
      - DJANGO_SECRET_KEY=NotImportantHere
      - WAIT_FOR_IT_ADDRESS=database:5432

volumes:
  database-volume: {}
