[tool.black]
target-version = ['py39']
line-length    = 88        # Black's default value
extend-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
# Compliance with Black is supported simply by using 'black' profile
# https://pycqa.github.io/isort/docs/configuration/black_compatibility
# https://pycqa.github.io/isort/docs/configuration/profiles/
profile = 'black'

# Configs not included in 'black' profile
py_version        = 39
atomic            = true
extend_skip_glob  = '*migrations*'

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'project.settings'
python_files           = ['tests.py', 'test_*.py', '*_tests.py']
addopts                = ['--verbose', '--reuse-db']
