# Generated by Django 3.2.13 on 2022-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0012_add_temporary_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Phone number"
            ),
        ),
    ]
