# Generated by Django 3.2.13 on 2022-09-21 06:12

from django.db import migrations
import encrypted_fields.fields


def migrate_data(apps, schema_editor):
    customer_model = apps.get_model("parking_permits", "Customer")
    for obj in customer_model.objects.all():
        obj.national_id_number = obj.old_national_id_number
        obj.save()


def reverse_migrate_data(apps, schema_editor):
    customer_model = apps.get_model("parking_permits", "Customer")
    for obj in customer_model.objects.all():
        obj.old_national_id_number = obj.national_id_number
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0013_allow_phone_number_to_be_null"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="national_id_number",
            new_name="old_national_id_number",
        ),
        migrations.AddField(
            model_name="customer",
            name="_national_id_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=50, verbose_name="National identification number"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="national_id_number",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="_national_id_number",
                hash_key="National identification number",
                max_length=66,
                null=True,
            ),
        ),
        migrations.RunPython(migrate_data, reverse_code=reverse_migrate_data),
    ]
