# Generated by Django 3.2.13 on 2022-11-24 16:21

from django.conf import settings
import django.contrib.postgres.fields.ranges
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("parking_permits", "0020_next_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingPermitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("RENEWED", "Renewed"),
                            ("ENDED", "Ended"),
                        ],
                        max_length=16,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("create_permit", "Create Permit"),
                            ("update_permit", "Update Permit"),
                            ("end_permit", "End Permit"),
                            ("create_order", "Create Order"),
                            ("renew_order", "Renew Order"),
                            ("create_refund", "Create Refund"),
                        ],
                        max_length=255,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "validity_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(null=True),
                ),
                ("object_id", models.PositiveBigIntegerField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "parking_permit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="parking_permits.parkingpermit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
