# Generated by Django 3.2.18 on 2023-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0022_alter_parkingpermitevent_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="talpa_logged_in_checkout_url",
            field=models.URLField(
                blank=True, verbose_name="Talpa logged in checkout url"
            ),
        ),
    ]
