# Generated by Django 3.2.18 on 2023-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0026_delete_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="talpa_last_valid_purchase_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Talpa last valid purchase time"
            ),
        ),
    ]
