# Generated by Django 3.2.18 on 2023-04-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0027_order_talpa_last_valid_purchase_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="_national_id_number",
        ),
        migrations.AlterField(
            model_name="customer",
            name="national_id_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="National identification number",
            ),
        ),
    ]
