# Generated by Django 3.2.18 on 2023-04-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0028_customer_national_id_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleuser",
            name="_national_id_number",
        ),
        migrations.AlterField(
            model_name="vehicleuser",
            name="national_id_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="National identification number",
            ),
        ),
    ]
