# Generated by Django 3.2.18 on 2023-04-19 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0029_vehicle_user_national_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_text",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="parking_zone_name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Parking zone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vehicles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=24),
                default=list,
                size=None,
                verbose_name="Vehicles",
            ),
        ),
    ]
