# Generated by Django 3.2.18 on 2023-05-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0031_add_create_by_modified_by_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="period_frequency",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="period_unit",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="start_date",
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RENEWAL_FAILED", "Renewal failed"),
                    ("USER_CANCELLED", "User cancelled"),
                ],
                max_length=20,
                null=True,
                verbose_name="Cancel reason",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="talpa_order_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Talpa order id",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="parking_permits.subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
