# Generated by Django 3.2.19 on 2023-05-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0032_subscription_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="permit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription",
                to="parking_permits.parkingpermit",
            ),
        ),
    ]
