# Generated by Django 3.2.19 on 2023-05-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0033_subscription_permit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="subscription",
        ),
        migrations.AddField(
            model_name="subscription",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="parking_permits.order",
                verbose_name="Order",
            ),
        ),
    ]
