# Generated by Django 4.2.1 on 2023-06-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0034_subscription_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="order",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="permit",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="talpa_order_id",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="parking_permits.subscription",
                verbose_name="Subscription",
            ),
        ),
    ]
