# Generated by Django 4.2.1 on 2023-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0036_orderitem_datetime_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="users",
            field=models.ManyToManyField(
                related_name="vehicles",
                to="parking_permits.vehicleuser",
                verbose_name="Vehicle users",
            ),
        ),
    ]
