# Generated by Django 4.2.1 on 2023-06-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0037_alter_vehicle_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="other_address_apartment",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Other address apartment"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="other_address_apartment_sv",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Other address apartment (sv)"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_address_apartment",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Primary address apartment"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="primary_address_apartment_sv",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Primary address apartment (sv)"
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="address_apartment",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Address apartment"
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="address_apartment_sv",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Address apartment (sv)"
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="next_address_apartment",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Next address apartment"
            ),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="next_address_apartment_sv",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Next address apartment (sv)"
            ),
        ),
    ]
