# Generated by Django 4.2.1 on 2023-07-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0038_address_apartment_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="other_address_apartment",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Other address apartment",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="other_address_apartment_sv",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Other address apartment (sv)",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="primary_address_apartment",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Primary address apartment",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="primary_address_apartment_sv",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Primary address apartment (sv)",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="address_apartment",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Address apartment"
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="address_apartment_sv",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Address apartment (sv)",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="next_address_apartment",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Next address apartment",
            ),
        ),
        migrations.AlterField(
            model_name="parkingpermit",
            name="next_address_apartment_sv",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Next address apartment (sv)",
            ),
        ),
    ]
