# Generated by Django 4.2.1 on 2023-08-29 08:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0039_nullable_apartments"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("street_name"),
                django.db.models.functions.text.Upper("street_number"),
                models.F("postal_code"),
                name="unique_address_fields",
            ),
        ),
    ]
