# Generated by Django 4.2.1 on 2023-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0040_address_unique_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("VEHICLE_CHANGED", "Vehicle changed"),
                    ("ADDRESS_CHANGED", "Address changed"),
                    ("SUBSCRIPTION_RENEWED", "Subscription renewed"),
                ],
                default="CREATED",
                max_length=50,
                verbose_name="Order type",
            ),
        ),
    ]
