# Generated by Django 4.2.1 on 2023-11-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0041_alter_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="permits",
            field=models.ManyToManyField(
                blank=True,
                related_name="refunds",
                to="parking_permits.parkingpermit",
                verbose_name="Permits",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="parking_permits.order",
                verbose_name="Order",
            ),
        ),
    ]
