# Generated by Django 4.2.1 on 2023-11-30 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0043_alter_subscription_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="restrictions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=2),
                default=list,
                size=None,
                verbose_name="Traficom Restrictions",
            ),
        ),
    ]
