# Generated by Django 4.2.1 on 2023-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0044_add_vehicle_restrictions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="low_emission_discount",
            field=models.DecimalField(
                decimal_places=10, max_digits=12, verbose_name="Low emission discount"
            ),
        ),
    ]
