# Generated by Django 4.2.1 on 2024-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0045_alter_product_low_emission_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="bypass_traficom_validation",
            field=models.BooleanField(
                default=False, verbose_name="Bypass Traficom validation"
            ),
        ),
    ]
