# Generated by Django 4.2.1 on 2024-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0046_add_bypass_traficom_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="updated_from_traficom_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Update from traficom on"
            ),
        ),
    ]
