# Generated by Django 4.2.1 on 2024-02-02 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0046_alter_vehicle_vehicle_class"),
        ("parking_permits", "0047_set_updated_from_traficom_null"),
    ]

    operations = []
