# Generated by Django 4.2.1 on 2024-02-08 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0049_alter_parkingpermit_status"),
        ("parking_permits", "0049_permit_extension_request"),
    ]

    operations = []
