# Generated by Django 4.2.1 on 2024-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0051_alter_parkingpermitextensionrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="end_type",
            field=models.CharField(
                choices=[
                    ("IMMEDIATELY", "Immediately"),
                    ("AFTER_CURRENT_PERIOD", "After current period"),
                    ("PREVIOUS_DAY_END", "Previous day end"),
                ],
                default="IMMEDIATELY",
                max_length=32,
                verbose_name="End type",
            ),
        ),
    ]
