# Generated by Django 4.2.1 on 2024-05-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0057_alter_vehicle_vehicle_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M1", "M1"),
                    ("M1G", "M1G"),
                    ("M2", "M2"),
                    ("M2G", "M2G"),
                    ("N1", "N1"),
                    ("N1G", "N1G"),
                    ("N2", "N2"),
                    ("N2G", "N2G"),
                    ("L3e-A1", "L3e-A1"),
                    ("L3e-A2", "L3e-A2"),
                    ("L3e-A3", "L3e-A3"),
                    ("L4e", "L4e"),
                    ("L5e-A", "L5e-A"),
                    ("L5e-B", "L5e-B"),
                    ("L6e-A", "L6e-A"),
                    ("L6e-B", "L6e-B"),
                    ("L6e-BP", "L6e-BP"),
                    ("L6e-BU", "L6e-BU"),
                ],
                max_length=16,
                verbose_name="VehicleClass",
            ),
        ),
    ]
