# Generated by Django 5.0.6 on 2024-08-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0058_alter_vehicle_vehicle_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="vat",
            field=models.DecimalField(
                decimal_places=4, default=0.24, max_digits=6, verbose_name="VAT"
            ),
        ),
    ]
