# Generated by Django 5.0.6 on 2024-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0059_refund_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="Last name"),
        ),
    ]
