# Generated by Django 5.0.6 on 2024-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0060_alter_customer_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="address_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="address_changed_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Address changed date"
            ),
        ),
    ]
