# Generated by Django 5.0.6 on 2024-09-17 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0061_parkingpermit_address_changed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="orders",
            field=models.ManyToManyField(
                related_name="refunds",
                to="parking_permits.order",
                verbose_name="Orders",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund",
                to="parking_permits.order",
                verbose_name="Order",
            ),
        ),
    ]
