# Generated by Django 5.0.6 on 2024-09-17 08:55

from django.db import migrations


def make_many_orders(apps, schema_editor):
    """
    Adds the Order object in Refund.order to the
    many-to-many relationship in Refund.orders.
    """
    Refund = apps.get_model("parking_permits", "Refund")

    for refund in Refund.objects.all():
        refund.orders.add(refund.order)


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0062_refund_orders_alter_refund_order"),
    ]

    operations = [
        migrations.RunPython(make_many_orders),
    ]
