# Generated by Django 5.0.6 on 2024-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0064_remove_refund_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="permits",
            field=models.ManyToManyField(
                related_name="refunds",
                to="parking_permits.parkingpermit",
                verbose_name="Permits",
            ),
        ),
    ]
