# Generated by Django 5.0.6 on 2024-09-25 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0065_alter_refund_permits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Time modified"),
                ),
                (
                    "active_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Active from"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Company code",
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="VAT code"
                    ),
                ),
                (
                    "internal_order",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Internal order",
                    ),
                ),
                (
                    "profit_center",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Profit center",
                    ),
                ),
                (
                    "balance_profit_center",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Balance profit center",
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Project"
                    ),
                ),
                (
                    "operation_area",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Operation area",
                    ),
                ),
                (
                    "main_ledger_account",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Main ledger account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting",
                "verbose_name_plural": "Accountings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="accounting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="parking_permits.accounting",
                verbose_name="Accounting",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="next_accounting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="next_products",
                to="parking_permits.accounting",
                verbose_name="Next accounting",
            ),
        ),
    ]
