# Generated by Django 5.0.6 on 2024-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0066_product_accounting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PRELIMINARY", "Preliminary"),
                    ("PAYMENT_IN_PROGRESS", "Payment in progress"),
                    ("VALID", "Valid"),
                    ("CANCELLED", "Cancelled"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
