# Generated by Django 5.0.6 on 2024-11-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0067_alter_parkingpermit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermitevent",
            name="key",
            field=models.CharField(
                choices=[
                    ("create_permit", "Create Permit"),
                    ("create_draft_permit", "Create Draft Permit"),
                    ("update_draft_permit", "Update Draft Permit"),
                    ("update_permit", "Update Permit"),
                    ("end_permit", "End Permit"),
                    ("create_order", "Create Order"),
                    ("renew_order", "Renew Order"),
                    ("create_refund", "Create Refund"),
                    ("add_temporary_vehicle", "Add Temporary Vehicle"),
                    ("remove_temporary_vehicle", "Remove Temporary Vehicle"),
                    (
                        "create_customer_permit_extension_request",
                        "Create Customer Permit Extension Request",
                    ),
                    (
                        "create_admin_permit_extension_request",
                        "Create Admin Permit Extension Request",
                    ),
                    (
                        "approve_permit_extension_request",
                        "Approve Permit Extension Request",
                    ),
                    (
                        "cancel_permit_extension_request",
                        "Cancel Permit Extension Request",
                    ),
                ],
                max_length=255,
            ),
        ),
    ]
