# Generated by Django 5.0.6 on 2024-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0068_alter_parkingpermitevent_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_refunded",
            field=models.BooleanField(default=False, verbose_name="Is refunded"),
        ),
    ]
