# Generated by Django 5.0.6 on 2024-12-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0069_orderitem_is_refunded"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="emails_handled",
            field=models.BooleanField(default=False, verbose_name="Emails handled"),
        ),
    ]
