# Generated by Django 5.1.9 on 2025-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0071_temporaryvehicle_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermitCountSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permit_count", models.IntegerField(verbose_name="Permit count")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "parking_zone_name",
                    models.CharField(max_length=128, verbose_name="Parking zone name"),
                ),
                (
                    "parking_zone_description",
                    models.TextField(verbose_name="Parking zone description"),
                ),
                (
                    "parking_zone_description_sv",
                    models.TextField(verbose_name="Parking zone description sv"),
                ),
                ("low_emission", models.BooleanField(verbose_name="Low-emission")),
                (
                    "primary_vehicle",
                    models.BooleanField(verbose_name="Primary vehicle"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("FIXED_PERIOD", "Fixed period"),
                            ("OPEN_ENDED", "Open ended"),
                        ],
                        max_length=16,
                        verbose_name="Contract type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permit count snapshot",
                "verbose_name_plural": "Permit count snapshots",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "date",
                            "parking_zone_name",
                            "parking_zone_description",
                            "parking_zone_description_sv",
                            "low_emission",
                            "primary_vehicle",
                            "contract_type",
                        ),
                        name="unique_daily_snapshot",
                    )
                ],
            },
        ),
    ]
