# Generated by Django 5.2.9 on 2026-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0072_permitcountsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_anonymized",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if customer data has been anonymized for GDPR compliance",
                verbose_name="Is anonymized",
            ),
        ),
    ]
