# Generated by Django 5.2.14 on 2026-06-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0073_customer_is_anonymized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="parking_permits.address",
                verbose_name="Address",
            ),
        ),
    ]
