# Generated by Django 5.2.15 on 2026-07-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0074_alter_company_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingpermit",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permits",
                to="parking_permits.vehicle",
                verbose_name="Vehicle",
            ),
        ),
    ]
