# Generated by Django 5.2.17 on 2026-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0075_alter_parkingpermit_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="updated_from_traficom_on",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Update from traficom on"
            ),
        ),
    ]
