# Generated by Django 5.2.17 on 2026-09-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0077_set_vehiclepowertype_fallback_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclepowertype",
            name="name",
            field=models.CharField(
                blank=True, default="Other", max_length=100, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
