# Generated by Django 5.2.17 on 2026-09-25 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0078_alter_vehiclepowertype_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="consent_low_emission_accepted",
        ),
    ]
