# Generated by Django 5.2.17 on 2026-09-29 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parking_permits", "0078_alter_vehiclepowertype_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LowEmissionCriteria",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="_is_low_emission",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="emission",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="emission_type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="euro_class",
        ),
    ]
