name: Continuous Integration

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: True
      DATABASE_URL: postgis://postgres:postgres@localhost/parking-permits
      DJANGO_SECRET_KEY: test-secret
      DJANGO_SETTINGS_MODULE: project.settings_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.9"
    - name: Install required Ubuntu packages
      run: |
        sudo apt-get install gdal-bin
    - name: Install PyPI dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Run Python side code neatness tests
      run: |
        flake8
        black --check .
        isort . -c

    services:
      postgres:
        image: postgis/postgis:13-3.3
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
